name: Nightly Build
on:
  schedule:
    - cron: '30 10 * * *' # 2:30AM PT/10:30AM UTC

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get upgrade -y && ${PWD}/utils/set_up_ubuntu.sh
      - run: make install
        #      - run: tar -cvzf ChimeraX.tar.gz ChimeraX.app
        #      - name: Upload the Built ChimeraX
        #        uses: actions/upload-artifact@v3.1.0
        #        with:
        #          name: ChimeraX-${{matrix.os}}.tar.gz
        #          path: ./ChimeraX.tar.gz
  build-centos-docker:
    runs-on: ubuntu-20.04
    container: 
      image: centos:latest
    steps:
      # https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
      - run: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      - run: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - run: dnf update -y
      - uses: actions/checkout@v3
      - run: ${PWD}/utils/set_up_centos.sh
      - run: make -f Makefile.centos install
  # TODO: Build Generic Linux
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
        # TODO: Notarize
        #      - run: tar -Jcvf ChimeraX.tar.xz ChimeraX.app
        #      - name: Upload the Built ChimeraX
        #        uses: actions/upload-artifact@v3.1.0
        #        with:
        #          name: ChimeraX-macOS.tar.xz
        #          path: ./ChimeraX.tar.xz
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-imagemagick mingw-w64-x86_64-binutils rsync patch unzip openssh make
      - run:
          # TODO: Freeze version to the production ChimeraX compiler
          AUTOMATIC_DISCOVERY=1 . ./vsvars.sh
          make install
